version: '3'
services:
#  app:
#    container_name: golang-restful-api
#    build: .
#    ports:
#      - 8080:8080
#    restart: on-failure
#    volumes:
#      - api:/usr/src/app/
#    depends_on:
#      - db-mysql
#    networks:
#      - backend

  db-mysql:
    image: mysql:5.7
    container_name: db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=customer_api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - backend

volumes:
  api:
  database_mysql:

networks:
  backend:
    driver: bridge
